server:
  port: 8089
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/hello_just/cloud-config-demo-repo
          username:
          password:
encrypt:  # 加密：http://localhost:8080/encrypt， 解密：http://localhost:8080/decrypt
  key: foo