server:
  port: 8070
spring:
  application:
    name: microservice-sidecar
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
sidecar:
  port: 8060
  health-uri: http://ocalhost:8060/health.json