server:
  port: 8086
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/hello_just/cloud-config-demo-repo
          username:
          password:
encrypt:
  keyStore:
    location: classpath:/server.jks
    password: letmein
    alias: mytestkey
#    secret: changeme