server:
  port: 8040
spring:
  application:
    name: microservice-gateway-zuul-fallback
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
logging:
  level:
    com.netflix: debug