server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/hello_just/cloud-config-demo-repo
security:
  basic:
    enabled: true
  user:
    name: user
    password: password123
