server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/hello_just/cloud-config-demo-repo
          username:
          password:
encrypt:
  key: foo